export const categories = [
  { id: 'start', name: 'Getting started', description: 'Install Editor, bring in your footage, and make the first cut.', number: '01' },
  { id: 'edit', name: 'Editing & workspace', description: 'Your timeline, your panels, your way of working.', number: '02' },
  { id: 'text', name: 'Titles & captions', description: 'Make every word readable, well timed, and yours.', number: '03' },
  { id: 'color', name: 'Color grading', description: 'Build a look with wheels, curves, nodes, and scopes.', number: '04' },
  { id: 'audio', name: 'Audio & mixing', description: 'Clean up, balance, automate, and deliver your sound.', number: '05' },
  { id: 'export', name: 'Export & handoffs', description: 'Finish a video or carry the timeline into your next app.', number: '06' },
  { id: 'support', name: 'Answers & troubleshooting', description: 'Find a fix, learn the shortcuts, and understand the details.', number: '07' },
];

// Editorial HTML is trusted, versioned source. Search uses plain text derived at build time.
export const articles = [
  { id: 'installation', category: 'start', title: 'Download and install Editor', description: 'Choose the right installer for macOS, Windows, or Linux, and understand first-launch prompts.', body: `
<h2>Choose your installer</h2><p>Open <a href="../../#download">Downloads</a> on this site. Version 0.2.0 is available for Apple Silicon and Intel Macs, 64-bit Windows PCs, and x86-64 Linux systems. The buttons download release files directly; you do not need a GitHub account.</p>
<h2>macOS</h2><ol><li>Open Apple menu → About This Mac. A chip named Apple M1, M2, or later uses the Apple Silicon download. A processor named Intel uses the Intel download.</li><li>Open the downloaded DMG and copy Editor to Applications.</li><li>Launch Editor from Applications.</li></ol><p>This community build is not notarized with an Apple developer signing certificate. If macOS blocks it, verify that you downloaded it from this site's download button, then review the app-specific approval in System Settings → Privacy & Security. Do not disable system-wide security protections. On managed computers, ask your administrator.</p><p>If you already use Homebrew, the package command is:</p><pre><code>brew install --cask koughen/editor/editor</code></pre>
<h2>Windows</h2><p>Use the EXE for a normal interactive installation. The MSI is an alternative installer for deployment workflows. Both target 64-bit Windows. The release does not have an Authenticode signing certificate, so Windows may show a publisher warning. Review the file source before deciding whether to allow it. Managed-device policies may require an administrator.</p><p>With Scoop installed, add the package bucket and install:</p><pre><code>scoop bucket add koughen https://github.com/koughen/scoop-editor\nscoop install koughen/editor</code></pre>
<h2>Linux</h2><p>Choose AppImage for a standalone launch, DEB for Debian/Ubuntu, or RPM for distributions using RPM packages. For AppImage, allow execution in the file's permissions, or run:</p><pre><code>chmod +x Editor_0.2.0_amd64.AppImage\n./Editor_0.2.0_amd64.AppImage</code></pre><p>Install a DEB or RPM with your distribution's package installer so dependencies can be resolved. Graphics and codec availability depend on your distribution, drivers, and webview runtime.</p>
<h2>Update and keep your work</h2><p>Keep your original source media and important exports backed up before updating. Download a newer installer for the same platform when one is available. Review <a href="../../releases/">release notes</a> for changes; local project storage is not a cloud backup.</p>` },
  { id: 'first-edit', category: 'start', title: 'Make your first video', description: 'A complete path from an empty project to your first exported scene.', image: 'edit', body: `
<h2>Start with a small project</h2><p>Open Editor and create a project from the project screen. A project holds your scenes and media. For a first edit, use a few short video files, an image, and an audio track. Set the canvas and frame rate in the project's settings before building the sequence.</p>
<h2>Build the story</h2><ol><li>In Edit, use Project → Media to import your footage.</li><li>Add media to the Timeline. Arrange clips in the order you want and use additional tracks for overlays and sound.</li><li>Move the playhead and press Space to preview. Select a clip and drag its edges to trim it.</li><li>Use Split at the playhead to create a cut. Remove the unwanted part and check the join.</li><li>Open Titles, enter your text and a duration, and choose a style. Select the title to adjust its appearance in Inspector.</li></ol>
<h2>Finish picture and sound</h2><p>Use Color for exposure, balance, and a consistent look across shots. Use Audio to balance the track levels and add fades. Start with small adjustments and compare with the original. A visual transition does not create an audio crossfade; audio fades have separate controls.</p>
<h2>Export the current scene</h2><p>Choose Export in the header. Start with MP4 and H.264 when your device supports it. Choose your resolution, frame rate, quality, and whether to include audio. Export the full scene or a custom range, then play the saved file to review the result.</p><p>Export covers the current scene. It does not automatically combine every scene in a project. For the next steps, read <a href="../timeline/">Timeline essentials</a> and <a href="../video-export/">Video export settings</a>.</p>` },
  { id: 'projects-media', category: 'start', title: 'Projects, media, and local storage', description: 'Understand scenes, imported media, saved work, and what to back up.', body: `
<h2>Projects and scenes</h2><p>A project contains scenes, project settings, and its media library. The scene selector in the Timeline lets you work on a scene. Edit, Color, and Audio are views into that work, so switching workspaces does not create separate copies of the timeline.</p>
<h2>Import and organize</h2><p>Project → Media is the home for imported footage, images, and audio. Sounds and Stickers have their own views in the Project sidebar, alongside Settings. Titles, Captions, Effects, and Transitions each have a dedicated dock panel. If one is missing, reopen it from Panels.</p><p>A file extension alone does not guarantee a file will decode. A video container can hold different codecs. If import or playback fails, first test a short, commonly supported H.264/AAC MP4 and compare it with the original file.</p>
<h2>Where the work lives</h2><p>Project data is stored locally in the app's webview storage. Imported media uses local browser-backed storage, including IndexedDB and origin-private file storage where available. Layout preferences and Color Gallery stills are also local, and Gallery stills are separate from project data.</p><p>No account is needed for the core editing workflow. This is not automatic cloud sync: a project on one device does not appear on another just because you install Editor there.</p>
<h2>Protect your work</h2><ul><li>Keep original footage and completed exports in folders you back up.</li><li>Do not clear application or webview storage as a routine troubleshooting step; it can remove local projects and media.</li><li>Watch free disk space. Large media imports and renders need additional room.</li><li>A handoff's source manifest is useful reference data, but it is not a documented one-click Editor backup/restore format.</li></ul><p>If storage is full, preserve your source files and exports before deleting anything. See <a href="../troubleshooting/">Troubleshooting</a> for a non-destructive first pass.</p>` },
  { id: 'timeline', category: 'edit', title: 'Timeline essentials', description: 'Trim, split, layer, select, snap, and keep picture and sound organized.', body: `
<h2>Arrange and preview</h2><p>The Timeline places media and text on tracks. Position clips along time to control when they appear, and use track order to build layers. Move the playhead to inspect a frame; Space or K toggles playback. The zoom controls change how much time is visible without changing clip duration.</p>
<h2>Trim and split</h2><p>Select a clip to edit it. Drag an edge to change the used portion, or put the playhead at a cut and use Split. The toolbar also provides Split left and Split right, which remove the corresponding side. Review the selected clips before applying an operation to multiple items.</p><p>Use snapping to align edges with nearby timeline positions. The default shortcut is N. Ripple editing is a separate timeline mode; check its state when you want subsequent material to move with an edit. Undo is available if the result differs from your intent.</p>
<h2>Copy, duplicate, and control tracks</h2><p>Copy selected elements and paste them at the playhead, or duplicate a selection. Mute controls affect sound; visibility controls affect picture. A hidden picture element and a muted audio element are different states. Bookmarks help identify timeline positions for later review.</p>
<h2>Separate source audio</h2><p>For supported video clips, the toolbar offers Extract audio or Recover source audio depending on the current state. This lets you work on the video's sound separately. Check alignment after moving either part so dialogue stays synchronized.</p>
<h2>Choose the right workspace</h2><p>Edit handles clip assembly, text, effects, and transitions. Color operates on a selected video or image. Audio mixes the scene's tracks. The header Export action delivers the current scene. Read <a href="../keyboard-shortcuts/">Keyboard shortcuts</a> for the default controls.</p>` },
  { id: 'workspace-layouts', category: 'edit', title: 'Arrange panels and save layouts', description: 'Dock, group, float, resize, maximize, and restore your eight editing panels.', body: `
<h2>The eight panels</h2><p>Edit includes Project, Viewer, Inspector, Timeline, Titles, Captions, Effects, and Transitions. Tools have one home each; the Project sidebar contains Media, Sounds, Stickers, and Settings.</p>
<h2>Move a panel</h2><ol><li>Grab its tab and drag it over another panel.</li><li>Drop in the center to group the two panels as tabs.</li><li>Drop on an edge to split that region.</li><li>Drag the divider between regions to resize them.</li></ol><p>The panel's ••• menu provides a Move panel selector as an alternative to dragging.</p>
<h2>Float, maximize, and reopen</h2><p>Float panel detaches a panel inside the editor window, with handles for moving and resizing it. It does not create a separate operating-system window. Double-click a tab or use its maximize control to expand it; repeat the action or press Escape to restore it.</p><p>Close panel hides it from the current arrangement. Reopen it through Panels. Closing a panel does not remove its clips, captions, or effects.</p>
<h2>Presets and saved workspaces</h2><p>Workspaces offers Editing, Captions, Effects, and Timeline presets. Save layout stores a named arrangement on this device; up to 12 named layouts are supported. The current arrangement persists between launches. Reset layout returns to the standard arrangement.</p><p>For a caption pass, put Captions beside the Viewer and keep the Timeline below. For detailed trimming, maximize the Timeline or use its preset. Layouts are device preferences, not a shared cloud workspace.</p>` },
  { id: 'effects', category: 'edit', title: 'Effects and adjustment layers', description: 'Apply a look, change stack order, animate controls, or affect a section with a layer.', body: `
<h2>Apply an effect</h2><ol><li>Open Effects from the dock or Panels menu.</li><li>Search or choose a category.</li><li>Choose Selected clips, select visual clips, and use a card's + button. You can also drag an effect onto a clip.</li><li>Select the clip and open Inspector → Effects to adjust it.</li></ol><p>Choose Adjustment layer to create a layer at the playhead instead. Its duration determines the section affected; position it over the material you want to treat.</p>
<h2>Available looks</h2><p>The library includes Gaussian blur, Color grade, Vignette, Film grain, Pixelate, Chromatic aberration, Sharpen, Sepia, Posterize, and Midnight / gold duotone. Mix lets you blend a look back toward the input.</p><p>Film grain uses a fixed spatial pattern. It is not a simulation of evolving analog grain. Check fine detail and gradients at your intended output size before applying strong stylization.</p>
<h2>Control the stack</h2><p>Inspector → Effects works on text as well as media. Reorder the stack with its earlier/later controls, bypass an effect for comparison, or remove it. Stack order changes the result: sharpening before blur differs from sharpening afterward.</p><p>Parameters that expose keyframe controls can change over time. Add a value, move the playhead, and set another value. Controls without animation support stay constant. Preview the entire affected section and review an export when using multiple heavy effects.</p><h2>Transitions are separate</h2><p>Transitions are applied after the clip's other effects. Use the <a href="../transitions/">Transitions panel</a> for entrances and exits, and Audio for sound fades.</p>` },
  { id: 'transitions', category: 'edit', title: 'Transitions between shots', description: 'Use dissolves, dips, wipes, iris, and zoom dissolves with predictable timing.', body: `
<h2>Add an entrance or exit</h2><ol><li>Select one or more visual clips.</li><li>Open Transitions.</li><li>Choose the entrance or exit edge and a duration.</li><li>Click Cross dissolve, Dip to black, Dip to white, a directional wipe, Iris, or Zoom dissolve.</li></ol><p>Yellow strips on the Timeline identify applied transitions. Click a strip to reopen the panel. None removes the selected edge; Remove both transitions clears the entrance and exit.</p>
<h2>What happens at a cut</h2><p>At adjacent video or image cuts on the same track, an incoming dissolve or reveal keeps the previous shot underneath the new one. It uses available source handles and holds the final source frame if those handles run out. The clip positions and overall timeline timing stay unchanged.</p><p>Other entrances and exits reveal underlying layers or the background. If you expected a dissolve between two shots but see black, check adjacency, track placement, and whether there is a visible layer beneath the transition.</p>
<h2>Duration and order</h2><p>A transition is limited to half the clip's duration, so a very short clip cannot carry a long entrance or exit. Transitions run after the clip's other effects. Preview both sides of the cut to catch an unexpected held frame or an overly long reveal.</p>
<h2>Sound does not follow automatically</h2><p>These are visual transitions. Use audio fades or <a href="../audio-automation/">Crossfade selection</a> for sound. Crossfades require overlapping audio on separate tracks and do not move the picture edit.</p>` },
  { id: 'masks-animation', category: 'edit', title: 'Transforms, masks, and animation', description: 'Frame your clips, control visible regions, and animate supported properties.', body: `
<h2>Transform a selected element</h2><p>Select media or text and use Inspector to adjust the available position, scale, rotation, opacity, and sizing controls. The Viewer helps you check the result in the scene's canvas. Project canvas dimensions and export dimensions are separate: export scales the completed scene, including its text and effects.</p>
<h2>Use a mask</h2><p>The mask library includes Rectangle, Ellipse, Diamond, Star, Heart, Split, Cinematic Bars, Text, and Custom. Masks control which part of an element is visible. Select a mask and adjust its available geometry and feathering controls; different shapes expose different parameters.</p><p>Keep a visible layer beneath the element when checking a cutout. Soft edges can blend into that layer, while an empty background may make them appear darker than expected. Custom paths and text masks should be reviewed closely when resizing or snapping.</p>
<h2>Add motion with keyframes</h2><ol><li>Select a property that has a keyframe control.</li><li>At the first timeline position, add a keyframe for its starting value.</li><li>Move the playhead and change the value for the next pose.</li><li>Preview between the positions and adjust the available interpolation or graph controls.</li></ol><p>Only supported properties animate. The Color workspace has its own node keyframe controls, and Audio uses automation lanes. A control's static value may be overridden when an animation lane is active.</p>
<h2>Speed and freeze frames</h2><p>Use Inspector's Speed section for supported media speed changes and the Timeline's freeze-frame tool when holding a frame. Recheck duration, neighboring cuts, and sound alignment after retiming. Editable application handoffs do not reproduce every animation curve or mask; use Preserve appearance when the rendered result matters most.</p>` },
  { id: 'titles', category: 'text', title: 'Create and style titles', description: 'Use eight editable styles and refine typography, outlines, shadows, and backgrounds.', body: `
<h2>Add text at the playhead</h2><ol><li>Open Titles, move the playhead to the insertion time, and enter your text.</li><li>Set the duration.</li><li>Choose Essential title, Editorial, Lower third, Clean subtitles, Yellow punch, Boxed captions, Electric, or End credits.</li><li>Select the new text element to refine it in Inspector.</li></ol>
<h2>Make the style yours</h2><p>Inspector provides font, color, weight, alignment, spacing, background, transform, and supported keyframes. Outline controls set the stroke color and width. Shadow controls set color, blur, and offsets. Check both bright and dark frames behind the title when choosing contrast.</p><p>Appearance sizes are based on a 1080p reference and scale with the canvas. A low-resolution output should preserve the title's proportions, though very fine strokes can become less readable at small sizes.</p>
<h2>Restyle existing text</h2><p>Select text elements and choose Style selected before applying a preset. This changes appearance while preserving their content, position, and timing. The same operation is useful for making captions consistent across a text track.</p>
<h2>Titles versus subtitle files</h2><p>Styled text is visible in the rendered video. SRT and VTT exports contain text and timing, without Editor's full appearance styling. Use video export for the look you built, or a subtitle sidecar when the receiving player or platform should handle presentation.</p>` },
  { id: 'captions', category: 'text', title: 'Generate and import captions', description: 'Transcribe locally or bring in SRT, VTT, and ASS subtitle files.', body: `
<h2>Generate from speech</h2><ol><li>Open Captions → Generate / import.</li><li>Choose the language and words-per-caption setting.</li><li>Start generation and allow the selected transcription model to download on first use.</li><li>Review the resulting cues in Edit cues, checking names, punctuation, timing, and quiet speech.</li></ol><p>Recognition runs locally after the model is available. The initial model download needs an internet connection and disk space. Generation accuracy depends on the recording and model; manually review captions before publishing.</p>
<h2>Import existing subtitles</h2><p>Import accepts SRT, VTT, and ASS. VTT import retains cue text and time ranges, removes markup, and ignores placement and region metadata as well as invalid cues. Imported subtitle presentation is not a promise of exact visual reproduction of another application's styling.</p>
<h2>Make the words readable</h2><p>Select the text track in Edit cues. Select a cue and refine its appearance in Inspector, or use Titles → Style selected to apply a consistent preset. Preview captions against the actual footage and keep line lengths comfortable for the intended output.</p>
<h2>If generation stalls or fails</h2><p>Check connectivity during the first download, available storage, and whether the source has usable speech audio. Try a short section or a smaller supported model if available. If recognition is unsuitable, import a prepared subtitle file and continue editing. See <a href="../caption-editing/">Edit and export caption cues</a> for corrections.</p>` },
  { id: 'caption-editing', category: 'text', title: 'Edit, split, merge, and export captions', description: 'Correct cue text and timing, resolve overlaps, and save plain subtitle sidecars.', body: `
<h2>Edit a cue</h2><p>In Captions → Edit cues, choose the text track. Search the cue list, select a cue, and change its text, start, or end time. Selecting or seeking a cue lets you compare it with the speech in the Viewer. You can add a cue or delete an unwanted one.</p>
<h2>Split and merge</h2><p>Move the playhead inside a cue and choose Split. A cue needs at least two words; words are divided proportionally at the selected time. This is not word-aligned speech recognition, so play the result and correct timing if needed.</p><p>Merge combines a cue with the next one and retains the first cue's appearance. Split, merge, and batch styling participate in timeline undo and redo.</p>
<h2>Why two captions appear together</h2><p>Overlapping cue intervals are allowed. If two captions appear simultaneously, check their start and end times, then inspect other visible text tracks for an additional title or imported copy. Shorten the unwanted overlap or remove the duplicate element.</p>
<h2>Choose your export</h2><p>Export SRT or Export VTT saves the selected track as a plain sidecar. These files carry text and timing, not the editor's outlines, shadows, backgrounds, or exact typography. Render the video to include that appearance. After a sidecar export, open it in the intended player or platform to verify timing and line breaks.</p><p>For an application handoff, XML destinations receive text separately as SRT. The destination may need the subtitle track imported as an additional step.</p>` },
  { id: 'color-workspace', category: 'color', title: 'Start a color grade', description: 'Understand the Color workspace, primaries, log controls, and the SDR pipeline.', image: 'color', body: `
<h2>Select a clip and a node</h2><p>Open Color beside Edit and choose a video or image from the clip strip. The workspace combines a Viewer, optional Gallery and serial-node panel, clip strip, optional Timeline, palette toolbar, and scopes. Each correction node is attached to the selected clip.</p>
<h2>Balance with primaries</h2><p>Lift, Gamma, Gain, and Offset wheels adjust different tonal regions or the overall balance. Drag a wheel or use its X/Y fields for keyboard entry. Y sliders and RGB bars offer additional numerical control. Start with exposure, temperature/tint, and contrast before refining saturation or a creative hue shift.</p><p>Available controls include contrast/pivot, shadows/highlights, hue, color boost, midtone detail, and luminance mix. Temperature and tint are relative adjustments, not camera Kelvin metadata. The numerical ranges and algorithms are Editor's own and do not match Resolve values one for one.</p>
<h2>Log tonal controls</h2><p>Log wheels use tonal weighting with adjustable low/high boundaries. They provide a way to target shadow, midtone, and highlight ranges in the current image. They do not switch the project into a scene-linear or log color-management pipeline.</p>
<h2>Compare and reset</h2><p>Bypass grades temporarily compares the scene without grading in the Viewer. It does not change the saved grade or export. Double-click a slider to reset that control, or use palette/node reset. Resetting a node also removes its numeric keyframes.</p>
<h2>Color-management limits</h2><p>Version 0.2.0 uses 8-bit display-referred SDR surfaces and clamps between serial nodes. It does not implement project-wide input/working/output color management, ACES, HDR mastering, camera RAW controls, or complete Resolve color-science parity. Camera-log footage needs an appropriate imported normalization LUT; check its input assumptions.</p>` },
  { id: 'color-nodes-curves', category: 'color', title: 'Nodes, curves, and channel mixing', description: 'Build a serial grade and shape contrast or color with targeted curves.', body: `
<h2>Build a serial node chain</h2><p>Add a serial node to separate a correction from the rest of the grade. Nodes process in order. Select, rename, disable, reset, delete, or move them Earlier/Later. Each node has its own primaries, curves, RGB mixer, qualifier, window, detail, LUT, key strength, and supported numeric animation.</p><p>A practical chain could separate basic exposure, a targeted color correction, and a final look. Bypass a node to compare its contribution. Unlike the Viewer-only Bypass grades control, node bypass is saved and affects export.</p>
<h2>Shape curves</h2><p>Custom curves include Y, R, G, and B. Targeted curves include Hue vs Hue/Saturation/Luminance, Luminance vs Saturation, and Saturation vs Saturation/Luminance. Click to add a point, drag or use arrow keys to move it, or edit its numeric values. Interior points can be removed; endpoint input positions stay fixed.</p><p>Curves use piecewise-linear interpolation sampled at 64 positions. There are no Bezier tangents, soft-clip controls, or curve animation in this release. Make gradual adjustments and review the scopes for clipping.</p>
<h2>RGB Mixer</h2><p>The mixer supplies a 3×3 channel matrix with monochrome, preserve-luminance, and normalization options. A channel's output can combine multiple input channels. Use small changes and inspect neutral areas; large coefficients can strongly alter brightness as well as color.</p>
<h2>Topology limits</h2><p>Processing is serial. Parallel, layer, splitter/combiner, shared nodes, group grades, and timeline-wide grading are not available. Use separate clip grades or adjustment effects appropriate to your edit.</p>` },
  { id: 'qualifiers-windows', category: 'color', title: 'Qualifiers, windows, and key strength', description: 'Limit a correction to a color range or region and inspect the selection matte.', body: `
<h2>Select a color range</h2><ol><li>Open the selected node's Qualifier palette and enable it.</li><li>Use the miniature Viewer picker to choose a starting color.</li><li>Refine hue, saturation, luminance, and shared softness.</li><li>Enable Highlight matte to inspect the selected region. White receives the correction; black retains the input.</li></ol><p>The picker samples the composited Viewer, while the shader tests the node's input. If a preceding or later effect changes the displayed color, refine the range numerically. Saturation selection uses HSV normalization and luminance uses Rec.709.</p>
<h2>Limit by position</h2><p>Power Windows offers ellipse, rectangle, and gradient shapes. Set pan/tilt, width/height, rotation, softness, and whether the correction is inside or outside. There is one window per node, adjusted through controls rather than direct Viewer handles.</p><p>The qualifier and window multiply together: an area must satisfy both to receive the combined correction. Use another serial node when a separate region needs different treatment.</p>
<h2>Blend the node</h2><p>Key output gain controls how strongly the complete node is mixed with its input. Zero keeps the input, including transparency. It is useful for reducing a finished correction without separately resetting every parameter.</p>
<h2>Know the limits</h2><p>Highlight matte is a monitor view and omits downstream effects on the selected clip; it is not exported. There is no automatic window/object tracking, Magic Mask, polygon/Bezier window, add/subtract qualifier sample set, or matte denoise/morphology. Animate supported window positions manually with keyframes.</p>` },
  { id: 'luts-scopes', category: 'color', title: 'LUTs, scopes, and detail controls', description: 'Import a 3D look, read image levels, and understand measurement limits.', body: `
<h2>Import a LUT</h2><p>The LUT palette accepts 3D .cube files with tables from 2 to 65 points per axis and domain minimum/maximum values. The node applies the LUT after its other adjustments using trilinear interpolation. Set the blend amount or remove it to compare.</p><p>Check whether the LUT expects camera log, a specific gamut, or an already normalized SDR image. Applying the wrong transform can crush contrast or distort colors. One-dimensional LUTs, shapers, and a built-in LUT preset browser are not supported.</p>
<h2>Choose a scope</h2><ul><li><strong>Luma waveform:</strong> compare brightness across the image width.</li><li><strong>RGB parade:</strong> examine the three channels side by side.</li><li><strong>RGB waveform overlay:</strong> compare channel levels in one display.</li><li><strong>RGB histogram:</strong> inspect the distribution of channel values.</li><li><strong>Vectorscope:</strong> inspect chroma distribution and direction.</li></ul><p>Adjust scope brightness and choose IRE, 8-bit, or 10-bit labels. Ten-bit labels are a display scale; they do not change the renderer to 10-bit processing.</p>
<h2>Measurement behavior</h2><p>Scopes sample the complete composited Viewer at roughly 7 Hz using a 256×144 input. They are practical monitoring tools, not a full-resolution HDR mastering instrument. There are no nits scales, HDR scopes, or multi-scope layout system in this release.</p>
<h2>Blur and sharpen</h2><p>Detail controls include blur radius, sharpen amount, mix, and midtone detail. These are lightweight spatial adjustments. Temporal noise reduction, per-channel mist/coring, and Resolve-style motion effects are not implemented. Inspect fine texture at the final viewing size to avoid halos or loss of detail.</p>` },
  { id: 'color-gallery-keyframes', category: 'color', title: 'Save looks and animate a grade', description: 'Use Gallery stills, reference wipes, copy/paste, and per-node numeric keyframes.', body: `
<h2>Grab a still</h2><p>Grab still saves a Viewer frame and the current clip's resolved grade in the local Gallery. Select a still for a movable reference wipe, or apply its grade to another clip. Reference images retain the canvas aspect ratio at a 960-pixel width; they are not full-resolution media exports.</p><p>The Gallery is stored locally in IndexedDB, outside individual projects. It is not automatically synchronized to another device or included as a portable PowerGrade library.</p>
<h2>Copy a look</h2><p>Copy/paste grade and Gallery apply transfer the values resolved at the current playhead, including the evaluated values of animated controls. They do not transfer the original animation timing. Choose a representative frame before copying a moving grade.</p>
<h2>Animate a numeric control</h2><ol><li>Open Keyframes and choose a supported control.</li><li>Add the first keyframe at the local playhead time.</li><li>Move the playhead and adjust the value.</li><li>Use Add/Update with linear or hold interpolation as appropriate.</li><li>Scrub the local timeline and review the keyframe list.</li></ol><p>Once a parameter is animated, ordinary palette adjustments update or add its value at the current local time. Delete unwanted keyframes from the list. Resetting the node removes its numeric animation.</p>
<h2>What remains static</h2><p>Curve shapes and LUT contents are static. Automatic tracking, grade versions, remote grades, shared nodes, PowerGrades interchange, and multi-image split screen are not available. Use the reference wipe and node bypass for practical comparisons.</p>` },
  { id: 'audio-workspace', category: 'audio', title: 'Mix tracks in the Audio workspace', description: 'Balance faders, pan, mute, solo, and effects across a scene.', image: 'audio', body: `
<h2>Open the mixer</h2><p>Choose Audio beside Edit and Color. The desk uses the project's video and audio tracks. Tracks, groups, returns, and stereo output each have a fader and pan control. Changes to effects, routing, automation, and buses save with the scene and use undo/redo.</p>
<h2>Set a balance</h2><ol><li>Play a representative section and start with dialogue or the main sound.</li><li>Bring music and other tracks up around it.</li><li>Use pan to place sound across the stereo image.</li><li>Mute a track to remove it from playback and export, or solo the material you need to inspect.</li></ol><p>Soloing a group includes its members. Muting a track also suppresses its sends. The master monitoring volume and the rendered mix level have different roles; use output loudness measurements to assess the signal being delivered.</p>
<h2>Shape a channel</h2><p>Effects includes EQ, compression, reverb, delay, and optional cleanup controls. Effects order changes the real processing chain. For example, putting reverb before a compressor can produce a different result from compressing the dry signal first.</p><p>Additional EQ bands adds up to eight individually enabled parametric, shelf, low/high-pass, or notch filters. Set frequency, gain, and Q while checking the response plot, then compare at a similar perceived level.</p>
<h2>Live or exact preview</h2><p>Live is responsive while editing. Render exact preview creates a continuous full mix with three seconds of extra tails so seeking preserves effect history. Re-render after changing the mix. See <a href="../loudness-preview/">Loudness and exact preview</a>.</p>` },
  { id: 'audio-cleanup', category: 'audio', title: 'Clean up dialogue and duck music', description: 'Use noise suppression, gate/expander, de-esser, and sidechain ducking carefully.', body: `
<h2>Start with the source</h2><p>Listen to an untreated section with speech, a pause, and a quiet ending. Cleanup controls are initially disabled so older projects remain neutral. Enable one process at a time and compare before adding another.</p>
<h2>Noise suppression and gate</h2><p>Noise reduction uses lightweight six-band downward suppression for steady background noise. Set its floor conservatively to preserve quiet detail. It is not trained voice isolation or a repair tool for clipped recordings, clicks, wind, or missing audio.</p><p>A gate/expander can reduce the level in quiet gaps. An aggressive setting may cut off consonants, breaths, or reverberation. Check the start and end of each phrase instead of judging only loud speech.</p>
<h2>Reduce sibilance</h2><p>The split-band de-esser reduces a targeted high-frequency region. Adjust while listening to words with strong “s” or “sh” sounds, then check that the voice has not become dull. EQ and compression may also change how much sibilance reaches it, so review effects order.</p>
<h2>Make music follow dialogue</h2><ol><li>On the music channel, enable Music ducking.</li><li>Select the dialogue track as the detector source.</li><li>Set threshold and attenuation, then adjust attack and release for a natural response.</li><li>Play sections with and without speech.</li></ol><p>The detector listens before the source track's fader and processing; muting the source disables detection. Stem exports preserve the original detector input even when only the music is exported.</p>` },
  { id: 'audio-routing', category: 'audio', title: 'Groups, returns, and sends', description: 'Organize tracks and share processing without creating feedback routes.', body: `
<h2>Route through a group</h2><p>In Routing, send a track to stereo output or a group. Use a group for related material such as dialogue or music so its combined level and processing can be adjusted together. Groups feed stereo output.</p><p>Group solo includes member tracks. Track and group mute/solo states affect export as well as playback, so clear temporary solos before delivering the full mix.</p>
<h2>Share an effect with a return</h2><p>Create a return and add a send from a track. New returns start with wet-only reverb; change the processing for delay or another shared effect. Adjust the send level to determine how much of the track enters it.</p><p>Pre-fader sends are taken before the track fader; post-fader sends follow its level. Choose according to whether the shared effect should change when you rebalance that source. Muting the source suppresses its sends.</p>
<h2>Routing constraints</h2><p>Groups and returns feed stereo output to keep the graph free of feedback cycles. Native Audio Unit inserts are available on source tracks and stereo output, not group or return buses. Built-in processing can be used on buses.</p>
<h2>Stems and shared processing</h2><p>Stems include track/group effects, sends, and original sidechain inputs, but omit master processing. Shared nonlinear processing can make recombined wet stems differ from the original complete mix. Deliver the stereo mix alongside stems when the final balance is important.</p>` },
  { id: 'audio-automation', category: 'audio', title: 'Automation, fades, and crossfades', description: 'Write precise level changes and smooth audio joins without moving the edit.', body: `
<h2>Automate a mix control</h2><p>Automation supports volume, pan, the original EQ, additional EQ-band parameters, compressor parameters, reverb send, and delay controls on tracks, buses, and master.</p><ol><li>Choose a control in Automation.</li><li>Add a point at the playhead or enter a timeline time.</li><li>Set its value and ramp/hold behavior.</li><li>Add another point, play the interval, and refine it.</li></ol><p>Active lanes override static controls. Disable Read automation to compare without deleting the points. Clip volume automation remains in the clip inspector.</p>
<h2>Fade a clip</h2><p>Use numeric durations or drag the audio-clip fade handles. Handles support keyboard arrow adjustments. Choose linear, equal-power, or S curves, then listen at the actual edit to judge the contour.</p>
<h2>Crossfade two clips</h2><p>Crossfade selection applies complementary equal-power fades to two clips whose end/start regions already overlap on separate tracks. Arrange that overlap first, select the two clips, and apply the command. It does not move clips or change picture synchronization.</p><p>A clip entirely contained inside another is not an end/start crossfade. If the command cannot apply, check that exactly the intended clips overlap at an outgoing and incoming edge.</p>
<h2>Review effect tails</h2><p>Reverb and delay can continue past a clip edge. Use an exact preview and choose an appropriate export tail when you need to hear or deliver the decay. A visual transition has separate timing and does not replace these sound controls.</p>` },
  { id: 'loudness-preview', category: 'audio', title: 'Loudness meters and exact preview', description: 'Read LUFS and true peak, analyze the full mix, and audition continuous processing.', body: `
<h2>Read the output meter</h2><p>The meter shows integrated, momentary, and short-term LUFS plus true peak in dBTP. It measures after master processing/limiting and before monitoring volume. Measurement begins with playback or Reset, freezes while paused, and resets after a seek.</p><p>Playback readings describe the portion you have played, not necessarily the whole scene. The analysis uses an EBU R128 / ITU BS.1770 implementation with gating and oversampled true peaks; no formal compliance certification is claimed.</p>
<h2>Analyze the whole program</h2><p>Analyze full mix measures the complete exported signal and also reports loudness range. Use it after the edit is stable, and compare the result with your destination's actual delivery requirements. A target selected in Editor is not a guarantee that every external platform will treat the file the same way.</p>
<h2>Render exact preview</h2><p>This renders a continuous full mix with three extra seconds of tails. Playback and seeking read that render, preserving the processing history at the chosen position. It is also the audition path for native Audio Units.</p><p>After changing a mix setting, render again. Live returns to the responsive built-in mixer; live seeks start fresh effect state. The rendered preview has an output loudness meter but does not reconstruct per-track peak meters.</p>
<h2>Normalization limits</h2><p>Audio export can target −14, −16, or −23 LUFS, while limiting added gain by a −1 dBTP ceiling. Highly dynamic material may finish below the requested loudness to respect that ceiling. Inspect the report rather than assuming the selected target was reached exactly.</p>` },
  { id: 'audio-units', category: 'audio', title: 'Use macOS Audio Unit effects', description: 'Scan native plug-ins, edit parameters, render a preview, and handle compatibility errors.', body: `
<h2>Scan and insert</h2><p>The macOS build hosts installed effect Audio Units through a separate rendering helper. Choose Scan installed effects, add an effect to a source track or stereo output, and adjust its generic parameters. Repeat instances, insert order, values, and bypass are stored with the scene.</p><p>Track inserts run before built-in channel effects. Stereo-output inserts run after the mixed output. Native inserts are not available on group or return buses.</p>
<h2>Audition the effect</h2><ol><li>Choose Render plug-in preview or the toolbar's Render exact preview.</li><li>Wait for the render, then play or seek through it.</li><li>After a parameter or mix change, render again.</li></ol><p>Exports render the current insert settings. The live built-in mixer is not a substitute for a newly rendered native plug-in preview.</p>
<h2>Supported interface</h2><p>This is an Audio Unit effect host, not a VST3 host. It provides generic parameter controls rather than the plug-in's custom window. Instruments, MIDI interfaces, and proprietary preset browsers are not implemented.</p>
<h2>If a plug-in fails</h2><p>Unavailable or offline-incompatible plug-ins produce an explicit render error. Bypass the suspect insert and render again to isolate it. Apple AULowpass has been verified, but compatibility and latency behavior are not guaranteed for every third-party effect.</p><p>Open the project in the macOS app to use native inserts. A web environment cannot silently discard them; they must be bypassed or rendered on a supported host.</p>` },
  { id: 'audio-export', category: 'audio', title: 'Export WAV, stems, and a loudness report', description: 'Choose sample rate, bit depth, tails, normalization, and separate track/group files.', body: `
<h2>Choose the audio format</h2><p>Open the Audio workspace's Export inspector. Stereo WAV export supports 44.1, 48, and 96 kHz with 16-bit PCM, 24-bit PCM, or 32-bit float encoding. Choose settings that match the delivery workflow; a higher sample rate does not recover detail missing from the source.</p>
<h2>Set the tail and level</h2><p>Choose 0–30 seconds of extra tail for reverb or delay decay. Keep current levels or normalize the stereo mix to −14, −16, or −23 LUFS. The normalizer only adds as much gain as a −1 dBTP ceiling permits, so a dynamic mix can remain below the chosen loudness target.</p>
<h2>Include stems</h2><p>Include separate track and group stems creates timeline-aligned files with their channel/group effects, sends, and original sidechain inputs. Stems omit master processing and preserve original relative gain. Muted or non-soloed tracks render silence, matching the mixer.</p><p>Shared nonlinear group/return processing means summing wet stems may not perfectly reproduce the complete mix. Include the stereo render as the reference and communicate whether the receiving engineer should rebuild bus processing.</p>
<h2>Find the result</h2><p>On macOS, audio files and a JSON loudness report are saved in a new folder under Downloads/Editor Exports. In a browser environment, the stereo mix downloads as WAV; a mix plus stems downloads as an uncompressed ZIP. Review the files and report after export.</p>` },
  { id: 'video-export', category: 'export', title: 'Video export settings', description: 'Understand formats, codecs, resolution, frame rate, bitrate, audio, and ranges.', image: 'export', body: `
<h2>Choose a container and codec</h2><p>Export in the header opens the destination workspace for the current scene. MP4 supports H.264, HEVC, and AV1; WebM supports VP9 and AV1, depending on the device's available encoders. Availability is checked before rendering. An unsupported choice returns an error rather than silently switching codecs.</p>
<h2>Resolution and frame rate</h2><p>Use a preset or custom even dimensions from 16 to 7680 pixels. Choose the project rate or a custom fractional rate. Fit preserves the entire picture with space when aspect ratios differ; Fill crops to cover the output; Stretch changes the proportions.</p><p>The scene renders at its original canvas size, then scales for encoding. Text, transforms, and effects retain their geometry when output resolution changes. The final partial frame is retained. Output is opaque SDR, without HDR mastering or transparent-video delivery.</p>
<h2>Quality and bitrate</h2><p>Choose a quality preset or target bitrate, constant or variable bitrate, keyframe interval, and a hardware preference. The size estimate is based on target rates, so actual file size can differ. More bitrate can preserve detail, but it cannot restore detail absent from the original media.</p>
<h2>Audio and custom ranges</h2><p>Enable or disable sound and choose AAC/Opus bitrate, 44.1/48 kHz, and mono/stereo where offered. A custom in/out range starts the exported video at zero and trims the mixed audio to the same source interval.</p>
<h2>Verify the deliverable</h2><p>Editor checks encoded frame counts before reporting success. Encoder operations have a watchdog and cancellation can interrupt pending encoding. Play the result to confirm picture, sound, timing, and dimensions. For an export failure, see <a href="../troubleshooting/">Troubleshooting</a>.</p>` },
  { id: 'application-handoffs', category: 'export', title: 'Send a timeline to another editor', description: 'Understand editable transfers, preserved appearance, package contents, and fidelity limits.', body: `
<h2>Two ways to transfer</h2><p><strong>Keep clips editable</strong> transfers supported cuts, trims, track ordering, fractional rates, basic transforms, opacity, mute state, simple speed changes, and clip gain. Read Transfer notes before exporting: destination interchange formats cannot reproduce every feature.</p><p><strong>Preserve appearance</strong> renders the final composite and stereo mix to a high-quality H.264/AAC file, then cuts that render at the original edit boundaries. The segments remain adjustable, but overlapping layers, text, grades, effects, and mix processing are baked into the media. Original sources can optionally be included.</p>
<h2>Package contents</h2><p>Packages contain collected media, destination-specific timeline files or scripts, a source-project.json manifest, handoff.json, and import notes. Names are made collision-safe. A browser environment downloads a ZIP; desktop can write a folder under Downloads/Editor Exports.</p>
<h2>What stays behind in editable mode</h2><p>Keyframe curves, masks, grades, advanced effects/mixing, generated graphics, and application-specific text styling do not become equivalent native effect controls. XML text is supplied separately as SRT. Non-uniform XML scaling is approximated using horizontal scale. Review retimed clips in the destination.</p>
<h2>Choose a destination</h2><ul><li><a href="../premiere-resolve/">Premiere Pro and DaVinci Resolve</a> use Final Cut Pro 7 XML.</li><li><a href="../after-effects-capcut/">After Effects</a> uses a JSX composition builder.</li><li><a href="../after-effects-capcut/">CapCut</a> uses an experimental Python draft builder.</li></ul><p>Launching an app does not always complete its import step. No existing destination project is overwritten. Keep the package's media alongside its timeline references.</p>` },
  { id: 'premiere-resolve', category: 'export', title: 'Import into Premiere Pro or DaVinci Resolve', description: 'Move an XML timeline, media, and timed subtitles into your next project.', body: `
<h2>Prepare the package</h2><p>Choose the destination in Export, select Keep clips editable or Preserve appearance, and review Transfer notes. Save the package and leave its media folder intact. Use a new destination project while checking the transfer.</p>
<h2>Premiere Pro</h2><ol><li>Open Premiere Pro and import timeline.xml from the package.</li><li>Resolve any media links using the package's collected media.</li><li>Import the timed SRT separately when using editable text.</li><li>Check cuts, transforms, speed, and sound, then save as a .prproj.</li></ol>
<h2>DaVinci Resolve</h2><p>Use Resolve's Import Timeline command with timeline.xml, or use the optional import-resolve.py when Resolve scripting is enabled. Opening Resolve from Editor may still require one of those import steps.</p><p>Review the imported frame rate and timeline settings, relink packaged media if requested, and bring in SRT text separately. Grades from Editor do not appear as an editable Resolve node tree. Preserve appearance is the route for retaining the rendered look.</p>
<h2>Check fidelity</h2><p>XML transfers supported timeline properties rather than complete native projects. Advanced effects, masks, animation, and mixing may differ. Non-uniform scale is approximated using horizontal scale, and speed changes should be checked against the reference. Read the package's detailed notes before replacing an existing workflow.</p>` },
  { id: 'after-effects-capcut', category: 'export', title: 'Import into After Effects or CapCut', description: 'Use the generated scripts and understand the experimental CapCut adapter.', body: `
<h2>After Effects</h2><ol><li>Export an After Effects package and keep its media folder beside the scripts.</li><li>In After Effects, choose File → Scripts → Run Script File.</li><li>Run the supplied JSX composition builder.</li><li>Inspect the composition and save the resulting project as .aep.</li></ol><p>macOS may block automatic control of another application. The JSX stays available for manual import. The transfer does not create native equivalents of every Editor effect, caption style, grade, or animation curve.</p>
<h2>CapCut is experimental</h2><p>The package includes an optional Python draft builder. Install pycapcut in your own Python environment, then run the supplied importer with your CapCut drafts directory, following the package notes. Editor does not install Python dependencies automatically.</p><p>CapCut's draft schema is not a stable public interchange contract. The upstream adapter primarily targets Windows, and Mac draft compatibility varies. Work in a test draft and keep your original project.</p>
<h2>Use the appearance video as a fallback</h2><p>If a CapCut draft does not open, import the rendered appearance MP4 as normal media. It retains the finished visual and audio result, though its effects are baked. The generated draft uses a full-length background lane to prevent magnetic main-track behavior from removing deliberate leading gaps.</p>
<h2>Review after import</h2><p>Check the first and last frame, leading gaps, overlays, text, speed, and audio synchronization. Preserve appearance and editable transfer make different tradeoffs; see <a href="../application-handoffs/">the handoff guide</a> before choosing.</p>` },
  { id: 'troubleshooting', category: 'support', title: 'Troubleshooting common problems', description: 'Recover a layout, diagnose silent audio, fix captions, and narrow down render failures.', body: `
<h2>A panel is missing or the layout is awkward</h2><p>Open Panels and enable the missing tool. Use Workspaces for a preset or Reset layout for the standard arrangement. Escape exits a maximized panel. Floating panels remain inside the main app window.</p>
<h2>Two captions appear at once</h2><p>Check overlapping cue start/end times in Captions → Edit cues. Inspect other visible text tracks for duplicates. Overlap is allowed, so simultaneous captions can be intentional. Remove the extra cue or adjust its interval.</p>
<h2>The mix is silent or does not follow the fader</h2><p>Check clip and track mute, active solos, group routing, and stereo-output level. Active automation can override a static control. A muted sidechain source disables ducking detection. After changing native plug-ins or an exact preview mix, render the preview again.</p>
<h2>Export reports an unsupported codec</h2><p>Encoder support varies by platform and runtime. Try another supported container/codec, such as H.264 MP4 where available. Lower the output dimensions or try a short custom range to isolate a resource issue. Editor does not silently substitute a codec.</p>
<h2>Export stalls or a file looks incomplete</h2><p>Cancel the job, check free storage, and retry a short range. Isolate a problematic clip, heavy effect, or native Audio Unit by bypassing it temporarily. Encoded frames are checked before success, so an error may indicate dropped frames or an unresponsive encoder. Review the exact error text.</p>
<h2>The grade differs between preview and export</h2><p>Turn off Viewer-only Bypass grades and Highlight matte before comparison. Saved node bypass affects both preview and export. Confirm you exported the intended scene/range. External players and displays may also present color differently.</p>
<h2>A project or media appears missing</h2><p>Confirm that you opened the same app installation and device. Preview builds can use separate local storage. Do not clear app data to diagnose this. Preserve originals and exports, then check disk space and any earlier storage warnings.</p>
<h2>Keep useful diagnostic details</h2><p>Record Editor version, operating system, what you clicked, expected and actual behavior, the exact error, and whether a short sample reproduces it. Avoid including private footage or personal data in public reports. This Help Center does not upload files or submit support tickets.</p>` },
  { id: 'keyboard-shortcuts', category: 'support', title: 'Keyboard shortcuts and accessible controls', description: 'Default editing keys, panel alternatives, and precise keyboard adjustments.', body: `
<h2>Playback and navigation</h2><div class="table-scroll"><table><thead><tr><th>Action</th><th>Default key</th></tr></thead><tbody><tr><td>Play / pause</td><td>Space or K</td></tr><tr><td>Seek back / forward one second</td><td>J / L</td></tr><tr><td>Previous / next frame</td><td>Left / Right arrow</td></tr><tr><td>Jump back / forward five seconds</td><td>Shift + Left / Right</td></tr><tr><td>Timeline start</td><td>Home or Enter</td></tr><tr><td>Timeline end</td><td>End</td></tr></tbody></table></div>
<h2>Editing</h2><div class="table-scroll"><table><thead><tr><th>Action</th><th>Default key</th></tr></thead><tbody><tr><td>Split selected elements</td><td>S</td></tr><tr><td>Split and remove left / right</td><td>Q / W</td></tr><tr><td>Delete selection</td><td>Backspace or Delete</td></tr><tr><td>Toggle snapping</td><td>N</td></tr><tr><td>Copy / paste / duplicate</td><td>Ctrl + C / V / D</td></tr><tr><td>Select all</td><td>Ctrl + A</td></tr><tr><td>Undo</td><td>Ctrl + Z</td></tr><tr><td>Redo</td><td>Ctrl + Shift + Z or Ctrl + Y</td></tr><tr><td>Cancel an interaction</td><td>Escape</td></tr></tbody></table></div><p>These are the source defaults. Check the in-app shortcut dialog for platform-specific display and your customized bindings. Text fields receive normal text-editing input while focused.</p>
<h2>Alternatives to dragging</h2><p>Panel ••• menus include Move panel. Color wheels provide X/Y fields. Curves support arrow-key movement and numeric point edits. Audio fades support numeric duration and keyboard arrows. Use those controls when a precise pointer gesture is difficult.</p>
<h2>This Help Center</h2><p>Search works with a normal text input; use Tab to reach results and Enter to open them. Workspace preview tabs on the home page support Left/Right/Home/End. Menus and dialogs close with Escape. Reduced-motion preferences are respected.</p>` },
  { id: 'faq', category: 'support', title: 'Frequently asked questions', description: 'Pricing, accounts, offline work, formats, captions, color, plug-ins, privacy, and more.', body: `
<h2>Cost, accounts, and devices</h2><h3>Is Editor free? Is there a watermark?</h3><p>Yes, the current release is free and open source. There is no paid feature tier or export watermark.</p><h3>Do I need an account?</h3><p>No account is required for the desktop editing workflow or this Help Center.</p><h3>Does it work offline?</h3><p>Core local editing runs on your computer. App downloads, online assets/fonts, and an initial transcription model download need network access. Cache availability can affect whether a previously used online resource is available offline.</p><h3>Is there a mobile or hosted browser editor?</h3><p>The downloadable release is for macOS, Windows, and Linux. This site is a product tour and Help Center, not a hosted editing session or mobile app.</p>
<h2>Picture and text</h2><h3>Can I rearrange every panel?</h3><p>The eight Edit panels can be docked, grouped, floated inside the app window, resized, and saved in layouts. Color and Audio have their own workspace organization.</p><h3>Can I import captions?</h3><p>Yes: SRT, VTT, and ASS. Plain SRT/VTT exports preserve timing and text; video rendering preserves Editor's caption appearance.</p><h3>Is the Color page identical to Resolve?</h3><p>No. It offers familiar grading tools with independent SDR algorithms. HDR/ACES workflows, automatic tracking, RAW controls, parallel node topology, and several advanced Resolve tools are not implemented.</p><h3>Why doesn't a 10-bit scope setting change the image precision?</h3><p>It changes label scaling only. The current rendering surfaces are 8-bit SDR.</p><h3>Can I animate a LUT or curve?</h3><p>LUT contents and curve shapes are static. Supported numeric node controls can be keyframed.</p>
<h2>Sound and export</h2><h3>Does noise reduction isolate any voice?</h3><p>No. It suppresses steady noise with a lightweight multiband algorithm and cannot reconstruct missing or clipped speech.</p><h3>Does Editor host VST3?</h3><p>No. The macOS build hosts effect Audio Units using generic parameter controls and rendered previews.</p><h3>Why is an audio export below the selected LUFS target?</h3><p>The normalizer limits added gain to respect a −1 dBTP ceiling. Highly dynamic material can therefore remain below target.</p><h3>Why doesn't a visual dissolve fade the sound?</h3><p>Visual transitions and audio fades are separate. Apply audio fades or an overlapping two-track crossfade.</p><h3>Why is my preferred video codec unavailable?</h3><p>Encoding depends on the device and runtime. Choose another supported option; Editor will not silently substitute a codec.</p><h3>Does export include all scenes?</h3><p>No. Video export uses the current scene, optionally restricted to a custom in/out range.</p><h3>Will another editor receive all my effects as editable controls?</h3><p>No. Editable handoffs preserve supported timeline properties. Preserve appearance renders the final look and mix into media instead.</p>
<h2>Files and support</h2><h3>Are projects synchronized or uploaded?</h3><p>Projects and imported media are stored locally for the core workflow. There is no automatic cloud project sync. Optional network resources have their own requests; see <a href="../../privacy/">Privacy</a>.</p><h3>Can I use Editor commercially?</h3><p>The MIT software license permits commercial use. Rights to your footage, music, fonts, plug-ins, and other materials are separate.</p><h3>Where should I start when something fails?</h3><p>Use <a href="../troubleshooting/">Troubleshooting</a> and test a small example. Keep the error message, version, and reproduction steps. Do not clear local app storage as a first step.</p>` },
  { id: 'open-source', category: 'support', title: 'About Editor and open source', description: 'The project’s license, origins, release model, and ways to contribute.', body: `
<h2>A desktop tool you can inspect</h2><p>Editor builds on OpenCut and is distributed under the MIT license. Version 0.2.0 adds dedicated creative workspaces, dockable editing panels, expanded text and caption tools, effects, transitions, and application handoffs.</p>
<h2>What the license allows</h2><p>You can use, copy, modify, distribute, sublicense, and sell the software under the license's conditions, including retaining the required notices. The software is provided without warranty to the extent permitted by law. Read the complete <a href="../../terms/#software-license">license on this site</a>.</p><p>Your footage and output remain subject to the rights in the material you use. The software license does not grant ownership of third-party media, music, fonts, plug-ins, or trademarks.</p>
<h2>Learn and contribute</h2><p>The project is in active development. Helpful contributions include clear reproduction steps, testing platform-specific behavior, improving documentation, accessibility review, and code changes. Keep private media out of public reports and use a minimal sample you have permission to share.</p><p>Source code is available as a <a href="https://github.com/koughen/Editor/archive/refs/heads/main.zip">direct ZIP download</a>. This is developer source, not an installer. Most visitors should use <a href="../../#download">the desktop downloads</a>.</p>
<h2>Release expectations</h2><p>Early releases can have platform-specific limitations. Review the <a href="../../releases/">release notes</a>, keep important source footage backed up, and verify exported files before relying on a delivery. There is no promise of a particular release schedule or compatibility with every third-party application.</p>` },
];
