export const policies = [
  { path: 'privacy', title: 'Privacy', eyebrow: 'YOUR FILES. YOUR CALL.', description: 'How the Editor website and desktop app handle local files, network requests, and third-party services.', body: `
<p class="article-intro">Editor is built around local creative work. This page explains what the current website does, where desktop projects live, and which actions involve other services.</p>
<h2>Scope and operator</h2><p>This notice covers the Editor project website and describes the core desktop workflow in version 0.2.0. “Editor” means this open-source project and its maintainers. Third-party hosts, downloads, online resources, and destination applications have separate privacy practices.</p>
<h2>Using this website</h2><p>The website has no account system, advertising, analytics scripts, tracking pixels, or tracking cookies. Fonts, product screenshots, help articles, and the search index are served as static site assets. The site does not ask to access your camera, microphone, location, or local project files.</p><p>Help Center searches are evaluated in your browser against a downloaded article index. Search terms are not submitted to an AI service or an Editor search server. The caption and layout demos only change the page's display. They do not upload media or save a project.</p>
<h2>Hosting and downloads</h2><p>GitHub Pages hosts the site, and GitHub serves the downloadable release files. A request to either host necessarily exposes connection information such as your IP address, requested resource, and browser information to that provider. GitHub may process service and security logs under its own retention practices. Editor's static site does not set or control those retention periods. Read <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub's privacy statement</a> for the provider's details.</p>
<h2>Desktop projects and media</h2><p>The core editing workflow stores project data and imported media on your device using the application's local webview storage. Layout preferences and Gallery stills are also stored locally. Editing does not require an Editor account, and the core workflow does not automatically upload your project to an Editor cloud service.</p><p>Local storage is not a cloud backup. Deleting a project, clearing app/webview data, removing a device profile, or losing access to the device may remove your work. Keep original source files and important exports backed up. Gallery stills and layout preferences are separate from individual project data.</p>
<h2>Optional network resources</h2><p>Initial caption-model downloads and optional online fonts or asset sources require network requests to their providers. Those providers receive ordinary request information. Caption recognition uses the downloaded model locally; the core transcription worker does not send your recording to a hosted transcription API.</p><p>Third-party plug-ins and destination applications can have their own network behavior. Exporting or handing off a project writes the content you select to output files; what you do with those files afterward is under your control. Review a third-party application's policy before providing it with personal or sensitive material.</p>
<h2>Support information and your choices</h2><p>This site has no support upload form or ticket backend. Reading help and searching articles does not submit a support request. If you choose to contact a maintainer through an external channel, that channel's policy applies to what you share. Use a minimal example and omit private footage, credentials, and unnecessary personal information.</p><p>You can use the local editing tools without choosing online resources. You can delete local projects through the app and manage app storage through your device; make a backup before clearing storage. Editor's maintainers cannot remotely retrieve or delete a project that exists only on your device. For provider-held request data, use the rights and contact options in the provider's notice.</p>
<h2>Changes</h2><p>This notice may change if hosting, optional services, or product behavior changes. The date below identifies this version. We will describe new collection features here when they are introduced rather than treating this notice as consent to undisclosed processing.</p>` },
  { path: 'terms', title: 'Terms', eyebrow: 'CLEAR TERMS. CREATIVE FREEDOM.', description: 'Terms for the Editor website, software license, your content, and third-party resources.', body: `
<p class="article-intro">These terms describe use of the Editor project website and the licensing of the software. Editor is free, open-source software. There is no subscription or paid service offered by this site.</p>
<h2>Website and documentation</h2><p>You may browse the product information, read the Help Center, and download available software. Use the site lawfully and do not interfere with its availability or misuse its infrastructure. Documentation describes the named release and can change as the project develops.</p><p>The site and documentation are provided as available, without a promise of uninterrupted availability, a support response time, or suitability for a particular production. No purchase, account, or click-to-accept contract is required to read the site.</p>
<h2>Your content and rights</h2><p>You keep the rights you have in your original content. Using Editor does not grant its maintainers ownership of your footage, projects, or exports. You are responsible for obtaining the rights and permissions needed to use, modify, and distribute your media, music, fonts, and other materials.</p><p>The software license permits commercial use, but it does not grant licenses to third-party content or imply approval by people depicted in that content. Review exported work before publishing, especially automatic captions, effects, timing, and application transfers.</p>
<h2>Third-party materials and applications</h2><p>Stock footage shown on this site is used in product demonstrations under its source license. It is not offered as a standalone stock download. Fonts are distributed with their license notices. Application names identify supported handoff destinations; they do not imply sponsorship, affiliation, or endorsement.</p><p>External hosts, plug-ins, libraries, and destination apps are governed by their own terms. Their availability and compatibility can change. Experimental transfers, including CapCut drafts, may require manual adjustment or fail in a particular version.</p>
<h2>Early software and responsibility</h2><p>Editor is actively developed. Keep backups of original media and important deliverables. No specific performance, export compatibility, data-recovery capability, or release schedule is guaranteed. To the extent permitted by applicable law, the software's warranty and liability provisions are those in its MIT license below. Nothing on this page excludes rights or liabilities that cannot lawfully be excluded.</p>
<h2 id="software-license">Software license</h2><p>The following license governs the Editor code and associated software documentation. It is not replaced or restricted by this website's general information.</p><pre class="license-text">__MIT_LICENSE__</pre>
<h2>Privacy and updates</h2><p>Read <a href="../privacy/">Privacy</a> for the site's operation, local project storage, and optional external requests. Changes to website terms apply to the updated website; they do not retroactively replace the license supplied with software you already received.</p>` },
];
