import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { articles, categories } from '../content/help.mjs';
import { policies } from '../content/policies.mjs';

const escapeHTML = ({ text }) => String(text).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const plainText = ({ html }) => html.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim();
const categoryFor = ({ id }) => categories.find((category) => category.id === id);

function pageShell({ title, description, base, path, body, siteURL, help = false }) {
  return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0b0b0b"><title>${escapeHTML({ text: title })} — Editor</title><meta name="description" content="${escapeHTML({ text: description })}"><link rel="canonical" href="${siteURL}${path}/"><meta property="og:title" content="${escapeHTML({ text: title })} — Editor"><meta property="og:description" content="${escapeHTML({ text: description })}"><meta property="og:type" content="website"><meta property="og:url" content="${siteURL}${path}/"><meta property="og:image" content="${siteURL}media/edit-workspace.png"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="${base}media/editor-icon.png"><link rel="preload" href="${base}fonts/manrope.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="${base}styles.css"><link rel="stylesheet" href="${base}help.css"><script type="module" src="${base}help.js"></script></head><body class="document-page"><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><a class="brand" href="${base}" aria-label="Editor home"><img src="${base}media/editor-icon.png" alt="" width="38" height="38"><span>editor<span class="brand-period">.</span></span></a><nav class="document-nav" aria-label="Main navigation"><a href="${base}help/" ${help ? 'aria-current="page"' : ''}>Help Center</a><a href="${base}releases/">What’s new</a></nav><a class="button button-small button-yellow" href="${base}#download">Get Editor <span aria-hidden="true">↗</span></a></header>
<main id="main" tabindex="-1">${body}</main>
<footer class="doc-footer page-width"><a class="brand" href="${base}" aria-label="Editor home"><span>editor<span class="brand-period">.</span></span></a><nav aria-label="Footer"><a href="${base}help/">Help Center</a><a href="${base}releases/">What’s new</a><a href="${base}privacy/">Privacy</a><a href="${base}terms/">Terms</a><a href="${base}help/open-source/">Open source</a></nav><p>Free tools. Your next great story.</p></footer></body></html>`;
}

function withHeadings({ body }) {
  const headings = [];
  const html = body.replace(/<h2(?: id="([^"]+)")?>(.*?)<\/h2>/g, (_, existing, label) => {
    const id = existing || plainText({ html: label }).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    headings.push({ id, label });
    return `<h2 id="${id}">${label}<a class="heading-anchor" href="#${id}" aria-label="Link to ${escapeHTML({ text: plainText({ html: label }) })}">#</a></h2>`;
  });
  return { html, headings };
}

function articleBody({ article, base, policy = false }) {
  const { html, headings } = withHeadings({ body: article.body });
  const category = policy ? 'PROJECT INFORMATION' : categoryFor({ id: article.category }).name;
  const related = policy ? [] : articles.filter((item) => item.id !== article.id && item.category === article.category).slice(0, 3);
  return `<div class="page-width article-wrap"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="${base}">Editor</a><span aria-hidden="true">/</span>${policy ? '<span>Project information</span>' : `<a href="${base}help/">Help Center</a><span aria-hidden="true">/</span><a href="${base}help/#${article.category}">${category}</a>`}</nav><div class="article-grid"><article class="article-content"><header class="article-header"><p class="eyebrow">${category}</p><h1>${article.title}</h1><p>${article.description}</p><div class="article-meta"><span>${policy ? 'Updated September 18, 2026' : 'FOR EDITOR 0.2.0'}</span><span>${Math.max(2, Math.ceil(plainText({ html }).split(' ').length / 200))} MIN READ</span></div></header>${article.image ? `<figure class="article-figure"><img src="${base}media/${article.image}-1440.jpg" srcset="${base}media/${article.image}-480.jpg 480w, ${base}media/${article.image}-960.jpg 960w, ${base}media/${article.image}-1440.jpg 1440w" sizes="(max-width: 800px) calc(100vw - 48px), min(800px, 65vw)" alt="Editor ${article.image} workspace showing the Coastal Drift stock-media project" width="1225" height="768"><figcaption>The ${article.image} workspace in Editor 0.2.0. Product preview with updated branding.</figcaption></figure>` : ''}${html}${related.length ? `<aside class="related-articles"><p class="eyebrow">KEEP GOING</p>${related.map((item) => `<a href="../${item.id}/">${item.title}<span aria-hidden="true">↗</span></a>`).join('')}</aside>` : ''}<div class="article-end"><a href="${base}help/">← All help topics</a><button type="button" class="print-article">Print this page</button></div></article><aside class="article-sidebar"><div class="toc"><p class="eyebrow">ON THIS PAGE</p><nav aria-label="On this page">${headings.map(({ id, label }) => `<a href="#${id}">${label}</a>`).join('')}</nav><a class="sidebar-search" href="${base}help/#search">Search the Help Center <span aria-hidden="true">↗</span></a></div></aside></div></div>`;
}

export async function buildContentPages({ outputDirectory, repoRoot, siteURL }) {
  const paths = ['help', 'privacy', 'terms', 'releases', ...articles.map(({ id }) => `help/${id}`)];
  const writePage = async ({ path, html }) => {
    await mkdir(resolve(outputDirectory, path), { recursive: true });
    await writeFile(resolve(outputDirectory, path, 'index.html'), html);
  };
  const catalog = categories.map((category) => `<section class="help-category" id="${category.id}" data-category-group="${category.id}"><div class="category-heading"><span class="category-number">${category.number}</span><div><h2>${category.name}</h2><p>${category.description}</p></div></div><div class="article-links">${articles.filter((article) => article.category === category.id).map((article) => `<a class="help-result" href="./${article.id}/" data-article="${article.id}"><div><h3>${article.title}</h3><p>${article.description}</p></div><span aria-hidden="true">↗</span></a>`).join('')}</div></section>`).join('');
  const helpBody = `<section class="help-hero page-width"><p class="eyebrow">EDITOR HELP CENTER</p><h1>LESS GUESSWORK.<br><span>MORE CREATING.</span></h1><p class="help-lede">From your first cut to the final export.<br>Practical guides for every part of your process.</p><div class="help-search" id="search"><label for="help-query">Search ${articles.length} guides</label><div class="search-field"><span aria-hidden="true">⌕</span><input id="help-query" type="search" placeholder="Try captions, color wheels, export…" autocomplete="off" spellcheck="false" aria-describedby="search-tip"><kbd aria-hidden="true">/</kbd></div><p id="search-tip">Search features, settings, or the problem you’re trying to solve.</p></div><div class="popular-topics"><span>START HERE</span><a href="./first-edit/">Your first video ↗</a><a href="./captions/">Add captions ↗</a><a href="./troubleshooting/">Find a fix ↗</a></div></section><section class="help-browser page-width" aria-label="Browse help articles"><div class="category-filters" role="group" aria-label="Filter by topic"><button data-filter="all" aria-pressed="true">All topics</button>${categories.map((category) => `<button data-filter="${category.id}" aria-pressed="false">${category.name}</button>`).join('')}</div><div class="search-summary"><p id="result-count" aria-live="polite">${articles.length} guides. Find your next step.</p><button id="clear-search" hidden>Clear search & filters</button></div><div id="no-results" class="empty-results" hidden><h2>Let’s try another angle.</h2><p>No matching guides. Try a shorter phrase, a control name, or browse all topics.</p><button class="button button-yellow" id="reset-search">Show all guides</button></div><div id="help-catalog">${catalog}</div><noscript><p>Search requires JavaScript. All guides are listed above and work without it.</p></noscript></section><section class="help-bottom page-width"><div><p class="eyebrow">LOOKING FOR A QUICK ANSWER?</p><h2>GOOD QUESTIONS.<br>CLEAR ANSWERS.</h2></div><a class="button button-yellow" href="./faq/">Read the full FAQ <span aria-hidden="true">↗</span></a></section>`;
  await writePage({ path: 'help', html: pageShell({ title: 'Help Center', description: 'Search practical guides for editing, captions, color grading, audio mixing, exports, and troubleshooting in Editor.', base: '../', path: 'help', body: helpBody, siteURL, help: true }) });
  await writeFile(resolve(outputDirectory, 'help/search-index.json'), JSON.stringify(articles.map((article) => ({ id: article.id, category: article.category, title: article.title, description: article.description, text: plainText({ html: article.body }) }))));
  for (const article of articles) {
    await writePage({ path: `help/${article.id}`, html: pageShell({ title: article.title, description: article.description, base: '../../', path: `help/${article.id}`, body: articleBody({ article, base: '../../' }), siteURL, help: true }) });
  }
  const license = await readFile(resolve(repoRoot, 'LICENSE'), 'utf8');
  for (const policy of policies) {
    const article = { ...policy, body: policy.body.replace('__MIT_LICENSE__', escapeHTML({ text: license })) };
    await writePage({ path: policy.path, html: pageShell({ title: policy.title, description: policy.description, base: '../', path: policy.path, body: articleBody({ article, base: '../', policy: true }), siteURL }) });
  }
  const releaseArticle = { title: 'A little more room to create.', description: 'Editor 0.2.0 brings the creative workflow together: picture, color, sound, and delivery.', body: `<div class="release-banner"><span>V0.2.0</span><a href="../#download">Download this release ↗</a></div><h2>Make your workspace yours</h2><p>Eight movable Edit panels, tab grouping, edge docking, resizable splits, in-window floating panels, maximize/restore, workspace presets, and up to 12 saved layouts. Captions, titles, effects, and transitions each have a dedicated home.</p><h2>Give every word its moment</h2><p>Eight title styles, outlines, shadows, backgrounds, and batch styling. Generate or import captions, edit cue timing, split and merge cues, and export plain SRT/VTT sidecars.</p><h2>Shape the finished picture</h2><p>A dedicated Color workspace with serial grading nodes, wheels, curves, RGB mixer, HSL qualifiers, windows, 3D LUT import, scopes, numeric animation, and Gallery comparisons. Expanded visual effects and clip entrance/exit transitions bring the edit together.</p><h2>Bring sound into balance</h2><p>Track and bus mixing, additional EQ bands, compression, reverb, delay, noise suppression, gate/expander, de-esser, sidechain ducking, routing, automation, fades, loudness analysis, WAV/stem delivery, and rendered native Audio Unit previews on macOS.</p><h2>Deliver or hand off</h2><p>More video controls for resolution, fractional frame rate, bitrate, audio, custom ranges, and hardware preferences. Transfer packages for Premiere Pro, Resolve, After Effects, and experimentally CapCut offer editable timelines or preserved rendered appearance.</p><h2>Before you begin</h2><p>This is early, actively developed software. The color pipeline is SDR, encoder availability depends on the platform, and editable handoffs cannot recreate every effect. Review the <a href="../help/installation/">installation guide</a> and <a href="../help/faq/">FAQ</a>, keep original media backed up, and check your exports.</p>` };
  await writePage({ path: 'releases', html: pageShell({ title: 'What’s new in Editor 0.2.0', description: releaseArticle.description, base: '../', path: 'releases', body: articleBody({ article: releaseArticle, base: '../', policy: true }), siteURL }) });
  const missingPage = pageShell({ title: 'Page not found', description: 'Find your way back to Editor or search the Help Center.', base: siteURL, path: '404', siteURL, body: `<section class="help-hero page-width"><p class="eyebrow">404 / A FRAME IS MISSING</p><h1>LET’S GET YOU<br><span>BACK ON TRACK.</span></h1><p class="help-lede">This page has moved or the address is incomplete.</p><div class="hero-actions" style="justify-content:flex-start"><a class="button button-yellow" href="${siteURL}help/">Search the Help Center ↗</a><a class="button button-outline" href="${siteURL}">Back to Editor</a></div></section>` }).replace('<meta name="description"', '<meta name="robots" content="noindex"><meta name="description"');
  await writeFile(resolve(outputDirectory, '404.html'), missingPage);
  return paths;
}
